name: driver_taxi
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_lints: ^4.0.0
  get: ^4.6.1
  # DateTime
  # jiffy: ^6.2.1
  # intl: ^0.19.0
  http: ^1.2.1
  # Images
  cached_network_image: ^3.2.0 
  image_picker: ^1.0.7
  # Animate
  # show_up_animation: ^2.0.0
  # auto_animated: ^3.0.1
  # Google Map
  # flutter_polyline_points: ^2.0.0
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  # Local Data Cache
  # sqflite: ^2.0.2
  shared_preferences: ^2.0.15
  # path: ^1.8.0
  # Qrcode 
  # qr_flutter: ^4.0.0
  # scan: ^1.6.0
  # grouped_list: ^5.1.2
  # url_launcher: ^6.1.2
  # dropdown_search: ^5.0.6
  # badges: ^3.1.2
  # Icon 
  # flutter_svg: ^1.0.3
  font_awesome_flutter: ^10.1.0
  fluttericon: ^2.0.0
  # dartz: ^0.10.1
  # Google Auth
  # google_sign_in: ^6.2.1  
  # device_preview: ^1.1.0
  responsive_builder: ^0.7.0
  # untitled4: ^0.0.1
  # flutter_keyboard_visibility: ^6.0.0
  google_fonts: ^6.2.1
  # flutter_map: ^6.1.0
  url_launcher:  ^6.2.5
  # workmanager: ^0.5.2
  permission_handler: ^11.3.1
  flutter_screenutil: ^5.7.0  
  loading_btn: ^1.0.3
  web_socket_channel: ^3.0.1
  #pusher_client: ^2.0.0
  # socket_io_client: ^3.0.0
  audioplayers: ^6.1.0
  #pusher_client_fixed: ^0.0.4+2
  #pusher_client: ^2.0.0
  #pusher_channels_flutter: ^2.2.1
  firebase_core: ^3.10.0
  firebase_messaging: ^15.2.0
  flutter_local_notifications: ^18.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/sound/notification.mp3

  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/Cairo-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
